schema: http://localhost:8080/graphql
documents: src/**/*.graphql
config:
  nonOptionalTypename: true
  onlyOperationTypes: true
  preResolveTypes: true
  reactApolloVersion: 3
  withHooks: false
  withComponent: false
  withHOC: false
extensions:
  codegen:
    generates:
      ./src/types.ts:
        plugins:
          - typescript
          - typescript-operations
          - typescript-graphql-request
